name: first_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs_on: ubuntu-latest
    steps:
      - name: Hello World and good bye
         run: |
          echo "Hello Naan da leo Das"
          echo "Good bye"
